Feature/load custom disease records
GeneDx/phenopy pull request #57
Opened 2020-10-05 17:47 UTC by vgainullin

2020-10-05 18:02 UTC, arvkevi requested changes

2020-10-05 18:02 UTC, arvkevi commented on phenopy/d2p.py
> +        return hpo_id_to_float.get(hpoa_frequency, 0.5)
If no frequency is given, we assume it's half? That seems strong. Can you put a `#TODO` here so we can come back and discuss the best default?

2020-10-05 18:02 UTC, arvkevi commented on phenopy/d2p.py
> +    return 0.5
same as above

2020-10-06 19:05 UTC, vgainullin commented on phenopy/d2p.py
> -                term_id = row['HPO_ID'] if row['HPO_ID'] not in alt2prim else alt2prim[row['HPO_ID']]
see line 120. this is still there, I will remove the comment

2020-10-06 19:05 UTC, vgainullin commented on phenopy/d2p.py
> +                term_id, disease_accession, freq = row
see line 120. this is still there, I will remove the comment

2020-10-06 19:32 UTC, merged